  - name: Demo on Loops
    hosts: localhost
    tasks:
      - name: Loop
        ansible.builtin.debug:
          msg: Fruit - {{ Item }}
        loop:
          - apple
          - banana
          - orange
